### PR TITLE
Improve vim hurl syntax

### PR DESCRIPTION
**Pull request by edg-l**
Not the best, but better than the current, it uses proper highlight definition links instead of hardcoded colors, so themes work better.

### CODE REVIEW

**Comment by jcamiel** [comment]
@edg-l would you be kind to rebase your branch on master? We keep a linear fit history and our CI wants your branch to be rebase. Thanks a lot

**Comment by edg-l** [comment]
You guys should check out bors, asking to rebase everytime master changes is not rly smth you should do. Bors does that for u

**Comment by jcamiel** [comment]
Yes sorry for this, your CI is rather strict. We’ve tried a lot of solutions but as we want our git history to be linear, each commit to be signed, our dependencies up-to-date etc… we’ve not yet a tool that fulfill perfectly our needs. Would you be kind to rebase your PR now, I’ve updated the Rust dependencies. We’ll try to improve the « Hurl PR process »

**Comment by edg-l** [comment]
done

**Pull request merged**
