### PR TITLE
Update zsh-completions

### PR DESCRIPTION
**Pull request by zottelsheep**
Updates the zsh completion file script in oder for zsh to:
- complete files
- accept long/short form arguments
- respect multiple arguments

### CODE REVIEW

**Comment by zottelsheep** [comment]
Hey @jcamiel, 
yeah that makes sense ':D I don't know why I didn't do that yesterday. But hey! at least now I know how to rebase a fork from an upstream repository (and how to sign my commits) :D

**Comment by zottelsheep** [comment]
Did clap really release a new version in the 10min after the other pull-requests went through ':D The crate-gods must really love this PR

**Comment by jcamiel** [comment]
Yes really sorry for the trouble... Maybe the simplest thing to do is to redo your PR on a branch, this way we can take care of the rest and you won't have to do anything else...

**Comment by zottelsheep** [comment]
Closing in favor of #2492

**Pull request closed without merging**
