### PR TITLE
Add test attributes to junit XML

### PR DESCRIPTION
**Pull request by joesantos418**
Hello,

I opened #1439 and was instructed to move the changes to another branch, run cargo clippy and sign the commit. I apparently can't update the old PR, so I'm creating this one, that hopefully has everything in order.

### CODE REVIEW

**Comment by jcamiel** [comment]
Hi @joesantos418 this is good, you just need to have your commits signed. On your branch, the state is "unverified" :

unverified

Maybe there is still sommething missing on your profile, you can check your account / Settings / SSH and GPG keys

**Comment by jcamiel** [comment]
FYI @joesantos418 I have a little time now and will work on this PR in the next days!

**Comment by jcamiel** [comment]
Hi @joesantos418 could you enable __Allow edits from maintainers__ on your fork (see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) so I can rebase your branch? Thanks a lot

**Comment by joesantos418** [comment]
Hi, I may have made a mistake. I wasn't seeing the pull request in my fork so I did a hard reset with the original repository and a push --force and now can't find my branch. What's the best course of action to avoid making this even worse? Sorry for the trouble.

**Comment by jcamiel** [comment]
I've your branch locally so I can make a new PR from this branch. You'll be the author of the changes so everything should be good. Let's try this !

**Comment by jcamiel** [comment]
@joesantos418 I've recreated the new PR here #1477 I'm closing this PR and will keep you inform for your progression!

**Comment by joesantos418** [comment]
Thank you

**Pull request closed without merging**
