### PR TITLE
Remove deprecated --fail-at-end option

### LINKED ISSUE #3430: Remove `--fail-at-end` deprecated option
`--fail-at-end` is deprecated for `--continue-on-error` since Sept. 2023, it's now a good time to remove it.

### PR DESCRIPTION
**Pull request by bp7968h**
This PR removes the `--fail-at-end` cli args for hurl

Closes #3430

### CODE REVIEW

**Comment by jcamiel** [comment]
You can search for all occurrence of `fail-at-end` in the project and remove them. There is at least this file `docs/spec/options/hurl/fail_at_end.option` that should be removed in this PR

**Comment by bp7968h** [comment]
Ohh, sorry I did not think about the docs. will do so thank you.

**Comment by jcamiel** [comment]
@bp7968h you should also try to build the project when you make some changes:

```shell
$ cargo build
$ cargo fmt
$ cargo clippy
```

I think the project is not building, you can see some CI/CD here => https://github.com/Orange-OpenSource/hurl/actions/runs/12039416760/job/33571179719?pr=3449

**Comment by bp7968h** [comment]
Hi @jcamiel, can you please approve the workflow on this one too, thank you.

**Comment by jcamiel** [comment]
Yes, can you squash the 2 commits for this PR? Thanks

**Comment by bp7968h** [comment]
Already done, thank you.

**Comment by jcamiel** [comment]
You can delete all files in `integration/hurl/tests_failed/fail_at_end*` as this integration test is not needed anymore

**Pull request merged**
