### PR TITLE
Hurl is now available on FreeBSD

### PR DESCRIPTION
**Pull request by rosorio**
Update project description to indicate how to install Hurd on FreeBSD

### CODE REVIEW

**Comment by jcamiel** [comment]
Hi @rosorio thanks a lot for the PR and the work on packaging Hurl fro FreeBSD! 
As stated in [contributing.md](https://github.com/Orange-OpenSource/hurl/blob/master/CONTRIBUTING.md), we require commits to be signed, could you please sign your commit to appease our CI?
I can assist you if you need any help

**Comment by rosorio** [comment]
Hi @jcamiel,

Yes, I notice the error, and signed my commit before pushing it again.
I just don't don't know if I did it the right/github way.

Cheers,
-- rodrigo

**Comment by jcamiel** [comment]
There is definitively something missing! On your commit, I can see this:

Screenshot 2022-12-02 at 17 40 33

[This link](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification) is a good start point for a check list. It must be a small thing, have you add your GPG ket to your GitHub profile (Profile / Settings / SSH and GPG keys)

**Comment by jcamiel** [comment]
Hi, don't forget to rebase also your commits, we need it in order to have a linear Git history. Once again, many thanks!

**Comment by rosorio** [comment]
Hi @jcamiel,
I follow the steps in git manual and now

- my commit is signed and verified (I can see the green check now)
- I rebase my commits

Sorry for the noise :)

**Comment by jcamiel** [comment]
Thanks a lot for the PR @rosorio the documentation is updated with FreeBSD now ! https://hurl.dev/docs/installation.html

**Pull request merged**
