### PR TITLE
Move xmllint check to check workflow

### PR DESCRIPTION
**Pull request by fabricereix**

### CODE REVIEW

**Comment by jcamiel** [comment]
@fabricereix don't know if it is normal that check workflow is failing?

**Comment by fabricereix** [comment]
With debugging, it seems that the directory in which the job is executed is `/home/runner/work/hurl/hurl` and does not contain any files.
Therefore, it can not find the script `bin/xmllint.sh`

**Comment by jcamiel** [comment]
In the workflow, the checkout repository is missing:

https://github.com/Orange-OpenSource/hurl/blob/a226282ce972fd48df6770e4fb1d81349d7615c5/.github/workflows/check.yml#L13

```
    - name: Checkout repository
      uses: actions/checkout@v2
```

**Comment by fabricereix** [comment]
OMG!
Thanks!!

**Pull request merged**
