### PR TITLE
Enable JUnit reports in CI

### PR DESCRIPTION
**Pull request by atcol**

### CODE REVIEW

**Comment by lepapareil** [comment]
Hi @atcol, it seems that the junit report publish is not working ?

image

**Comment by atcol** [comment]
Is this a token issue? See https://github.com/mikepenz/action-junit-report-legacy/issues/32

**Comment by lepapareil** [comment]
> Is this a token issue? See [mikepenz/action-junit-report-legacy#32](https://github.com/mikepenz/action-junit-report-legacy/issues/32)

It seems that the token is not readable in a pull request when actions are triggered from a fork.
However i forked your fork, i have created a full local pull request, and the result is as expected.
I will do some more checks from last fetched master branch and will validate it with @fabricereix 😄.

**Comment by lepapareil** [comment]
Hi @atcol,

Finally the junit report action doesn't give us much on our ci. Indeed we already have the errors details in jobs console output, moreover we have false positives in `checks` because of the real errors testing.

image

That's why we should not integrate the junit action for the moment.

**Pull request closed without merging**
