### PR TITLE
Fix graceful shutdown of workers threads in --test

### PR DESCRIPTION
**Pull request by jcamiel**

### CODE REVIEW

**Comment by chenrui333** [comment]
@jcamiel any chance of cutting a new release for this fix? I am having the similar issue with the github action runners.

**Comment by jcamiel** [comment]
Hi @chenrui333 is it OK with you? We try to release the next version at the end of November, it will include this bug fix. If I'm not mistaken, it should happens relatively infrequently.

**Comment by jcamiel** [comment]
Hi @chenrui333 6.0.0 version is out, available with this fix!

**Comment by chenrui333** [comment]
👋 sorry about late reply in here 😄 (I just bump internal hurl version to 6.0.0, and I will report back next week, if I have seen the issue or not). If you have not heard from me, that also means it is all good for us now.

**Comment by chenrui333** [comment]
> If I'm not mistaken, it should happens relatively infrequently.

yeah, it happened infrequently before, that is why it is a bit hard for me to capture something for bug reporting.

**Pull request merged**
